name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.repository == 'Nextc1/Next_Carbon_backend'
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            cd ~/backend
            git pull origin main
            pnpm install --frozen-lockfile
            pnpm run build
            pm2 restart 0
