name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.repository == 'Nextc1/Next_Carbon_backend'
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.bashrc
            cd ~/backend
            git pull origin main
            /home/ubuntu/.nvm/versions/node/v23.11.0/bin/pnpm install --frozen-lockfile
            /home/ubuntu/.nvm/versions/node/v23.11.0/bin/pnpm run build
            /home/ubuntu/.nvm/versions/node/v23.11.0/bin/pm2 restart 0
